# Generated by Django 5.1.6 on 2025-05-06 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bookings', '0004_bookingseats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('card', 'card'), ('netbanking', 'netbanking')], max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], max_length=100)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.bookings')),
            ],
        ),
    ]
