# Generated by Django 5.1.6 on 2025-04-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0003_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seat_type',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('luxury', 'Luxury')], max_length=20),
        ),
    ]
