# Generated by Django 5.1.6 on 2025-04-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0004_alter_seats_seat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtimes',
            name='start_time',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
