# Generated by Django 5.1.6 on 2025-04-29 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0005_showtimes_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimes',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
