# Generated by Django 5.1.6 on 2025-04-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0006_alter_showtimes_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimes',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
