# Generated by Django 5.2 on 2025-04-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingseats',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingseats',
            name='seat',
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='BookingSeats',
        ),
    ]
