# Generated by Django 5.1.6 on 2025-04-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_initial'),
        ('Theatre', '0003_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.bookings')),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Theatre.seats')),
            ],
        ),
    ]
