# Generated by Django 5.1.6 on 2025-05-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_bookingseats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='Showtime',
            new_name='showtime',
        ),
    ]
