# Generated by Django 5.2 on 2025-04-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('romance', 'Romance'), ('thriller', 'Thriller')], max_length=255)),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('kannada', 'Kannada'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('malayalam', 'Malayalam')], max_length=255)),
                ('synopsis', models.TextField()),
                ('cast', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('release_date', models.DateField()),
                ('trailer_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
