# Generated by Django 5.1.6 on 2025-04-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
